spring.application.name=career_backend

spring.datasource.url=${CAREER_DB_URL:jdbc:mysql://192.168.118.130:3306/career_backend?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai}
spring.datasource.username=${CAREER_DB_USERNAME:root}
spring.datasource.password=${CAREER_DB_PASSWORD:123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

group.jwt.location=${JWT_KEYSTORE_LOCATION:classpath:hmall.jks}
group.jwt.alias=${JWT_KEY_ALIAS:hmall}
group.jwt.password=${JWT_KEYSTORE_PASSWORD:hmall123}
group.jwt.token-ttl=1d
