package group.careerservice.TestConstant;/* I love coding */

public class DeepEvalTestConstant {
    public static final String test_json = "{\n" +
            "   \"pathEdges\":[\n" +
            "      {\n" +
            "         \"source\":\"pn_1\",\n" +
            "         \"target\":\"pn_2\",\n" +
            "         \"relationType\":\"transition\",\n" +
            "         \"similarity\":0.71,\n" +
            "         \"difficulty\":\"medium\",\n" +
            "         \"reason\":\"需补齐后端工程与数据库能力\",\n" +
            "         \"inferred\":false\n" +
            "      },\n" +
            "      {\n" +
            "         \"source\":\"pn_2\",\n" +
            "         \"target\":\"pn_3\",\n" +
            "         \"relationType\":\"transition\",\n" +
            "         \"similarity\":0.66,\n" +
            "         \"difficulty\":\"medium\",\n" +
            "         \"reason\":\"需补齐机器学习工程化与部署能力\",\n" +
            "         \"inferred\":false\n" +
            "      }\n" +
            "   ],\n" +
            "   \"evaluation\":{\n" +
            "      \"level\":\"deep\",\n" +
            "      \"feasibilityScore\":78,\n" +
            "      \"readinessScore\":76,\n" +
            "      \"recommendationScore\":77,\n" +
            "      \"riskAlerts\":[\n" +
            "         \n" +
            "      ],\n" +
            "      \"aiCommentary\":\"该路径具备潜力，建议先补齐关键短板并优化过渡节点。\",\n" +
            "      \"stagePlans\":[\n" +
            "         {\n" +
            "            \"stage\":\"transitionPhase\",\n" +
            "            \"stageLabel\":\"过渡阶段\",\n" +
            "            \"cycle\":\"0-1个月\",\n" +
            "            \"goals\":[\n" +
            "               \"完成从职业起点到前端开发工程师的能力过渡\",\n" +
            "               \"建立前端开发工程师方向的基础证据（项目/作品/证书）\"\n" +
            "            ],\n" +
            "            \"suggestedTasks\":[\n" +
            "               {\n" +
            "                  \"title\":\"在和鲸社区完成一道每周挑战（数据方向）\",\n" +
            "                  \"linkText\":\"前往和鲸社区\",\n" +
            "                  \"linkUrl\":\"https://www.heywhale.com/\"\n" +
            "               },\n" +
            "               {\n" +
            "                  \"title\":\"在力扣完成2道与目标岗位相关题目，形成解题复盘\",\n" +
            "                  \"linkText\":\"前往力扣\",\n" +
            "                  \"linkUrl\":\"https://leetcode.cn/\"\n" +
            "               }\n" +
            "            ],\n" +
            "            \"metrics\":[\n" +
            "               \"输出1份阶段复盘（含能力差距与补齐动作）\",\n" +
            "               \"形成至少1项可展示成果并可用于面试讲述\"\n" +
            "            ]\n" +
            "         }\n" +
            "      ],\n" +
            "      \"summaryMetrics\":[\n" +
            "         {\n" +
            "            \"key\":\"avgSimilarity\",\n" +
            "            \"label\":\"路径平均相似度\",\n" +
            "            \"value\":78.0\n" +
            "         },\n" +
            "         {\n" +
            "            \"key\":\"nodeCount\",\n" +
            "            \"label\":\"路径节点数\",\n" +
            "            \"value\":3\n" +
            "         },\n" +
            "         {\n" +
            "            \"key\":\"targetMatch\",\n" +
            "            \"label\":\"目标岗位匹配度\",\n" +
            "            \"value\":76\n" +
            "         }\n" +
            "      ]\n" +
            "   }\n" +
            "}";

}
